Add support for Cloud Quota Management API
selectel/go-selvpcclient pull request #157
Opened 2022-11-17 21:40 UTC by T-Sh

To work with "limits" and "quotas", we now need to handle the Cloud Quota Management API instead of the Cloud Management API.

QuotaRegionalClient is a Proxy of the HTTP client. It resolves the URL of the service in the requested region and adds X-Auth-Token to the headers.

The functionality for issuing and caching the X-Auth-Token, as well as resolving the service URL is encapsulated in the IdentityManager.

2022-11-25 12:38 UTC, milkrage requested changes

2022-11-25 12:38 UTC, milkrage commented on selvpcclient/quotamanager/quotas/doc.go
> +Resell v2 API.
Этот файл тоже нужно прошерстить и убрать старые артефакты

2022-11-25 15:08 UTC, T-Sh commented on selvpcclient/quotamanager/quotas/schemas.go
> +	}
Поправила

2022-12-13 18:12 UTC, milkrage approved these changes

2022-12-14 10:25 UTC, merged