Add default region for Keystone and Resell API
selectel/go-selvpcclient pull request #169
Opened 2023-12-08 15:10 UTC by TruePack

2023-12-08 23:51 UTC, milkrage requested changes

2023-12-08 23:51 UTC, milkrage commented on selvpcclient/selvpc.go
> +
Теряется консистентность с подходом по указанию AuthURL в NewServiceClient.

Если стал прокидывать регион в Resell Client, тогда предлагаю сделать так:
1. Выбор значения AuthURL (указанное или дефолт) сделать в NewClient, в NewServiceClient сделать это поле обязательным. Можно заодно сменить имя на DefaultAuthURL.
2. В Resell Client переименовать authRegion в region (потому что для ResellAPI это не auth region).

2023-12-11 10:47 UTC, TruePack commented on selvpcclient/selvpc.go
> +
Поправил.

2023-12-11 16:41 UTC, milkrage commented on selvpcclient/clients/services/serviceclient.go
> +
Нужно убрать Optional параметр

2023-12-12 16:19 UTC, T-Sh approved these changes

2023-12-12 22:17 UTC, milkrage approved these changes

2023-12-13 12:08 UTC, merged